apiVersion: v1
kind: Service
metadata:
  namespace: {{ index .Values.global.namespace }}
  name: vantage6-server
spec:
  selector:
    app: vantage6-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
