apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vantage6-server
  namespace: control-plane
spec:
  hosts:
  - "*"
  gateways:
  - idea-gateway
  http:
  - match:
    - uri:
        prefix: /api/
    rewrite:
        uri: "/"
    route:
    - destination:
        host: vantage-server.control-plane.svc.cluster.local
        port:
          number: 5000